  meta:
    name: ActiveLearning_baseline
  AL_hyper:
    train_size: 200
    step: 10
  task:
    name: "3task"
  model:
    path: "EleutherAI/pythia-2.8b"
  dir:
    cache_dir: "/dccstor/yifei01/.cache/huggingface/"
    data_dir: "/u/duanyf99/multitask/ActiveLearning/baseline/Data/"
    model_dir: "/dccstor/yifei01/bu_multitask/ActiveLearning/baseline/"
  hyperparams:
    num_train_epochs: 20
    batch_size: 4
    learning_rate: 0.00002
    weight_decay: 0.01
  