  meta:
    name: InferenceUnannotated
  task:
    SFT: "3task"
    inference: "prod"
  scheme:
    name: "MultipleChoice"
    if_unknown: "with_unknown"
  MC_init:
    shuffle: 1
  dir:
    cache_dir: "/dccstor/yifei01/.cache/huggingface/"
    data_super_dir: "/u/duanyf99/multitask/"
    model_super_dir: "/dccstor/yifei01/bu_multitask/"
  model:
    path: "EleutherAI/pythia-2.8b"
    checkpoint: 7080