  meta:
    name: ActiveLearning
  dir:
    cache_dir: "/dccstor/yifei01/.cache/huggingface/"
    data_dir: "./data/AL/baseline/"
  model:
    path: "EleutherAI/pythia-2.8b"
  task:
    name: "3task"
  hyper:
    train_size: 200
    num_train_epochs: 50
    batch_size: 4
    learning_rate: 2e-5
    weight_decay: 0.01
  log:
    evaluation_strategy: "epoch"
    logging_strategy: "epoch"