  meta:
    name: SupervisedFineTuning
  task:
    name: "3task"
  scheme:
    name: "MultipleChoice"
    if_unknown: "with_unknown"
  dir:
    cache_dir: "/dccstor/yifei01/.cache/huggingface/"
    data_super_dir: "/u/duanyf99/multitask/"
    model_super_dir: "/dccstor/yifei01/bu_multitask/"
  model:
    path: "EleutherAI/pythia-2.8b"
  hyperparams:
    num_train_epochs: 20
    batch_size: 4
    learning_rate: 0.00002
    weight_decay: 0.01
  save:
    every_num_epoch: 1